export default [
  {
    id: 'moose',
    title: 'Лось',
    description: 'Наш лось не бодается, не убегает в лес и не ест соль.',
    top: 14,
    topM: 10,
  },
  {
    id: 'donkey',
    title: 'Осел',
    description: 'Этот ослик совсем не упрямый и его не нужно заманивать морковкой.',
    top: 14,
    topM: 10,
  },
  {
    id: 'ram',
    title: 'Баран',
    description: 'У нашего барашка есть свой нрав. Тем не менее, он не просто милый, а очень милый!',
    top: 10,
    topM: 8,
  },
  {
    id: 'elephant',
    title: 'Слон',
    description: 'Говорят, что слон неповоротливое животное. Только не этот!',
    top: 13,
    topM: 9,
  },
  {
    id: 'giraffe',
    title: 'Жираф',
    description: 'Настоящее сафари у вас дома? Не вопрос!',
    top: -6,
    topM: -2,
  },
  {
    id: 'unicorn',
    title: 'Единорог',
    description: 'Они бывают только в сказках? Как бы не так!',
    top: 9,
    topM: 9,
  },
  {
    id: 'horse',
    title: 'Лошадь',
    description: 'Кто из животных больше всего любит катать людей? Конечно лошадка!',
    top: 6,
    topM: 7,
  },
];
